### PR TITLE
Update README to indicate incompatibility with 2.1+

### PR DESCRIPTION
**Pull request by harrybiddle**
Due to #5, this library is only compatible up to Django 2.0.9. In this PR I have made this clear in the README.

### CODE REVIEW

**Comment by jarshwah** [comment]
Can you please also update setup.py classifiers?

https://github.com/kogan/django-lrucache-backend/blob/master/setup.py#L40

**Comment by harrybiddle** [comment]
Of course!

**Comment by harrybiddle** [comment]
OK, I have specified Django versions 2.0, presuming that this also covers 2.0.1, 2.0.2, etc. Is that correct, or do I also need to list the versions with the third version number?

**Comment by jarshwah** [comment]
MAJ.MIN is enough, no need to list the PATCH number also. Will review shortly and merge, thanks!

**Review by jarshwah — APPROVED** [review]

**Pull request merged**
